Repository googleapis/java-pubsub, pull requests merged in 2020-09, with the labels that each got.

#289 samples: subscription detachment
  samples/snippets/src/main/java/pubsub/DetachSubscriptionExample.java
  samples/snippets/src/main/java/pubsub/RemoveDeadLetterPolicyExample.java
  samples/snippets/src/test/java/pubsub/AdminIT.java
  samples/snippets/src/test/java/pubsub/DeadLetterQueueIT.java
Labels: cla: yes

#339 samples: add a comment to regional endpoint
  samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java
Labels: cla: yes

#340 fix: make subscriberIT test less flaky
  samples/snippets/src/test/java/pubsub/SubscriberIT.java
Labels: api: pubsub, cla: yes

#344 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#345 chore: regenerate common templates
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#347 samples: fix lint
  samples/snippets/src/test/java/pubsub/AdminIT.java
Labels: cla: yes

#346 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .github/workflows/samples.yaml
  .kokoro/release/stage.cfg
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: partial

#352 samples: add a region tag for docs
  samples/snippets/src/main/java/pubsub/CreateTopicExample.java
  samples/snippets/src/main/java/pubsub/PublisherExample.java
Labels: api: pubsub, cla: yes, samples

#366 fix: Ensure that messages that are in pending batches for an ordering key are canceled when a previous publish for the ordering keys fails
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: api: pubsub, cla: yes

#367 fix: Only check keyHasError if ordering key is non-empty
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#359 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#358 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: pubsub, automerge, cla: yes

#369 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#372 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
