Repository googleapis/java-pubsub, pull requests merged in 2020-07, with the labels that each got.

#211 feat: implement max duration per ack extension
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#277 test: Reuse method to publish a message in PublisherImplTest
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: cla: yes

#269 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  google-cloud-pubsub/pom.xml
  pom.xml
  synth.metadata
Labels: cla: yes, context: partial

#279 test: Replace deprecated method with non-deprecated one
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
Labels: cla: yes

#285 chore: README version update
  README.md
  synth.metadata
Labels: cla: yes, context: none

#288 chore: version update.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#293 fix: Make error message more clear about where ordering must be enabled when publishing
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#292 fix: if a flow control setting is not provided use zero
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: cla: yes

#294 add header providers to PublisherStubSettings
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes

#287 samples: publish with ordering keys
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithOrdering.java
  samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java
  samples/snippets/src/main/java/pubsub/ResumePublishWithOrderingKeys.java
  samples/snippets/src/test/java/pubsub/AdminIT.java
  samples/snippets/src/test/java/pubsub/PublisherIT.java
Labels: cla: yes, do not merge

#296 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#297 docs: remove experimental warning for ordering keys properties.
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessageOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Snapshot.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SnapshotOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: automerge, cla: yes, context: full
