Repository googleapis/java-pubsub, pull requests merged in 2020-06, with the labels that each got.

#227 samples: migrate publisher samples and add tests
  pom.xml
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/PublishWithBatchSettingsExample.java
  samples/snippets/src/main/java/pubsub/PublishWithConcurrencyControlExample.java
  samples/snippets/src/main/java/pubsub/PublishWithCustomAttributesExample.java
  samples/snippets/src/main/java/pubsub/PublishWithErrorHandlerExample.java
  samples/snippets/src/main/java/pubsub/PublishWithRetrySettingsExample.java
  samples/snippets/src/main/java/pubsub/ReceiveMessagesWithDeliveryAttemptsExample.java
  samples/snippets/src/main/java/pubsub/RemoveDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/UpdateDeadLetterPolicyExample.java
  samples/snippets/src/test/java/pubsub/PublisherIT.java
Labels: cla: yes

#229 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#216 feat: add detach subscription rpc
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockPublisherImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: cla: yes, context: partial

#232 chore: update common templates
  .kokoro/build.sh
  README.md
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#243 samples: add quickstart publish sample
  samples/snippets/src/main/java/pubsub/PublishWithBatchSettingsExample.java
  samples/snippets/src/main/java/pubsub/PublisherExample.java
  samples/snippets/src/test/java/pubsub/PublisherIT.java
Labels: cla: yes

#236 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#248 samples: migrate admin samples and add tests (part 3)
  samples/snippets/src/main/java/pubsub/CreatePullSubscriptionExample.java
  samples/snippets/src/main/java/pubsub/CreatePushSubscriptionExample.java
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/CreateTopicExample.java
  samples/snippets/src/main/java/pubsub/DeleteSubscriptionExample.java
  samples/snippets/src/main/java/pubsub/DeleteTopicExample.java
  samples/snippets/src/main/java/pubsub/GetSubscriptionPolicyExample.java
  samples/snippets/src/main/java/pubsub/GetTopicPolicyExample.java
  samples/snippets/src/main/java/pubsub/ListSubscriptionsInProjectExample.java
  samples/snippets/src/main/java/pubsub/ListSubscriptionsInTopicExample.java
  samples/snippets/src/main/java/pubsub/ListTopicsExample.java
  samples/snippets/src/main/java/pubsub/PublishWithBatchSettingsExample.java
  samples/snippets/src/main/java/pubsub/PublishWithConcurrencyControlExample.java
  samples/snippets/src/main/java/pubsub/PublishWithCustomAttributesExample.java
  samples/snippets/src/main/java/pubsub/PublishWithErrorHandlerExample.java
  samples/snippets/src/main/java/pubsub/PublishWithRetrySettingsExample.java
  samples/snippets/src/main/java/pubsub/PublisherExample.java
  samples/snippets/src/main/java/pubsub/SetSubscriptionPolicyExample.java
  samples/snippets/src/main/java/pubsub/SetTopicPolicyExample.java
  samples/snippets/src/main/java/pubsub/SubscribeAsyncExample.java
  samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java
  samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java
  samples/snippets/src/main/java/pubsub/SubscribeWithConcurrencyControlExample.java
  samples/snippets/src/main/java/pubsub/SubscribeWithCustomAttributesExample.java
  samples/snippets/src/main/java/pubsub/SubscribeWithErrorListenerExample.java
  samples/snippets/src/main/java/pubsub/SubscribeWithFlowControlSettingsExample.java
  samples/snippets/src/main/java/pubsub/TestSubscriptionPermissionsExample.java
  samples/snippets/src/main/java/pubsub/TestTopicPermissionsExample.java
  samples/snippets/src/main/java/pubsub/UpdatePushConfigurationExample.java
  samples/snippets/src/test/java/pubsub/AdminIT.java
  samples/snippets/src/test/java/pubsub/SubscriberIT.java
Labels: cla: yes

#253 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#246 feat: regenerated to pick up doc changes
  README.md
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessageOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: cla: yes, context: partial

#259 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-pubsub/pom.xml
  grpc-google-cloud-pubsub-v1/pom.xml
  pom.xml
  proto-google-cloud-pubsub-v1/pom.xml
Labels: cla: yes

#266 chore: Re-generated to pick up changes from googleapis
  README.md
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: cla: yes, context: partial

#267 feat: Send streaming pull flow control settings to server
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: cla: yes

#272 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
