Repository googleapis/java-pubsub, pull requests merged in 2020-08, with the labels that each got.

#298 chore(docs): add cloud rad
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#305 chore: update google-cloud-pubsub version
  README.md
  synth.metadata
Labels: cla: yes, context: none

#311 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#318 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#322 chore: increase README version
  README.md
  synth.metadata
Labels: cla: yes, context: none

#310 fix: ensure proper cleanup of publisher in tests
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Labels: api: pubsub, cla: yes
