Repository googleapis/java-pubsub, pull requests merged in 2020-12, with the labels that each got.

#456 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#459 fix: `setParallelPullCount` documentation
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: api: pubsub, cla: yes

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#470 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#471 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#473 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full, merge
