Repository googleapis/java-pubsub, pull requests merged in 2020-05, with the labels that each got.

#157 chore: update common templates, start generating README
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
  synth.py
Labels: cla: yes

#177 fix: typo in readme link to javadocs
  README.md
Labels: cla: yes

#186 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
Labels: cla: yes

#196 feat: set up repo for samples
  .kokoro/continuous/java11-samples.cfg
  .kokoro/continuous/jave8-samples.cfg
  .kokoro/nightly/java11-samples.cfg
  .kokoro/nightly/jave8-samples.cfg
  .kokoro/presubmit/java11-samples.cfg
  .kokoro/presubmit/jave8-samples.cfg
  .kokoro/run_samples_tests.sh
  pom.xml
Labels: cla: yes

#201 nit: fix typo in .kokoro/*.cfg
  .kokoro/continuous/jave8-samples.cfg
  .kokoro/nightly/jave8-samples.cfg
  .kokoro/presubmit/jave8-samples.cfg
Labels: cla: yes

#204 chore: set env vars for tests and make it executable
  .kokoro/nightly/java8-samples.cfg
  .kokoro/presubmit/java8-samples.cfg
  .kokoro/run_samples_tests.sh
Labels: cla: yes

#198 feat: implement google-cloud-shared-dependencies BOM
  google-cloud-pubsub/pom.xml
  pom.xml
Labels: cla: yes

#197 samples: add DLQ samples
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/ReceiveMessagesWithDeliveryAttemptsExample.java
  samples/snippets/src/main/java/pubsub/RemoveDeadLetterPolicyExample.java
  samples/snippets/src/main/java/pubsub/UpdateDeadLetterPolicyExample.java
  samples/snippets/src/test/java/pubsub/DeadLetterQueueIT.java
Labels: cla: yes

#192 docs(fix): update client documentation link
  .repo-metadata.json
Labels: cla: yes

#206 fix: update ignored diffs
  proto-google-cloud-pubsub-v1/clirr-ignored-differences.xml
Labels: cla: yes

#185 feat: regenerated to pick up changes in the API or client library generator
  CONTRIBUTING.md
  README.md
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSubscriberStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockPublisherImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSubscriberImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfigOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ReceivedMessage.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ReceivedMessageOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateTopicRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateTopicRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: cla: yes, context: full

#208 chore(java): allow overriding minimum supported Java version in templates (#577)
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#214 chore(java): fix inadvertent whitespace changes (#578)
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#218 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: automerge, cla: yes

#220 deps: remove grpc test dep since it's now in shared-deps
  pom.xml
Labels: automerge, cla: yes
