Repository googleapis/java-pubsub, pull requests merged in 2020-11, with the labels that each got.

#421 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#422 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#424 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#427 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#426 feat: Enable server side flow control by default with the option to turn it off
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: api: pubsub, cla: yes

#434 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#442 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#439 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#443 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#445 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#447 feat: make the stream ack deadline congruent with maxDurationPerAckExtension
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeSubscriberServiceImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: api: pubsub, cla: yes

#450 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full, samples
