Repository googleapis/java-pubsub, pull requests merged in 2021-08, with the labels that each got.

#757 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: pubsub, automerge, cla: yes

#760 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: pubsub, automerge, cla: yes

#753 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#761 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: cla: yes, api: pubsub, automerge

#767 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#780 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#790 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#792 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: pubsub, automerge, context: full

#794 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#795 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#798 chore: generate topic retention changes
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/gapic_metadata.json
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/package-info.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherCallableFactory.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSchemaServiceCallableFactory.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSchemaServiceStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSubscriberCallableFactory.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSubscriberStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SchemaServiceStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockIAMPolicy.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockIAMPolicyImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockPublisher.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockPublisherImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSchemaService.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSchemaServiceImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSubscriber.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSubscriberImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SchemaServiceClientTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectTopicName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriptionOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UntypedTopicName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaResponse.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/schema.proto
  synth.metadata
Labels: cla: yes, api: pubsub

#812 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#811 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: pubsub, automerge

#820 fix: Set publish timeouts to be consistent with desired values
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Labels: cla: yes, api: pubsub

#822 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge

#825 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: pubsub, automerge
