Repository googleapis/java-pubsub, pull requests merged in 2021-06, with the labels that each got.

#689 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#696 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#703 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#705 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#709 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#712 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#713 test: presubmit against Lite samples
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/presubmit/presubmit-against-pubsublite-samples.cfg
  synth.py
Labels: api: pubsub, cla: yes, samples

#718 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#721 fix: allow retries for subscriber unary rpcs
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: api: pubsub, cla: yes

#720 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#717 samples: add publish with flow control sample
  samples/snippets/src/main/java/pubsub/PublishWithFlowControlExample.java
  samples/snippets/src/test/java/pubsub/PublisherIT.java
Labels: api: pubsub, cla: yes, samples

#727 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes
