Repository googleapis/java-pubsub, pull requests merged in 2021-05, with the labels that each got.

#641 ci: setup workflows for new release branch
  .github/workflows/ci.yaml
Labels: api: pubsub, cla: yes

#642 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: none

#640 build: configure branch 1.111.0-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: pubsub, cla: yes

#645 samples(test): add retry rule in tests
  samples/snippets/src/test/java/pubsub/DeadLetterQueueIT.java
Labels: api: pubsub, cla: yes, samples

#650 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#653 chore(1.111.0-sp): release 1.111.0-sp.1-SNAPSHOT
  google-cloud-pubsub-bom/pom.xml
  google-cloud-pubsub/pom.xml
  grpc-google-cloud-pubsub-v1/pom.xml
  pom.xml
  proto-google-cloud-pubsub-v1/pom.xml
  samples/snapshot/pom.xml
  versions.txt
Labels: api: pubsub, cla: yes, type: process

#657 chore(1.111.0-sp): release 1.111.0-sp.1
  CHANGELOG.md
  google-cloud-pubsub-bom/pom.xml
  google-cloud-pubsub/pom.xml
  grpc-google-cloud-pubsub-v1/pom.xml
  pom.xml
  proto-google-cloud-pubsub-v1/pom.xml
  samples/snapshot/pom.xml
  versions.txt
Labels: api: pubsub, autorelease: pending, cla: yes

#661 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#662 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#668 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#671 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#673 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#676 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#677 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#683 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#686 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes
