Repository googleapis/java-pubsub, pull requests merged in 2021-03, with the labels that each got.

#551 feat(generator): update protoc to v3.15.3
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequestOrBuilder.java
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#554 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#555 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#539 fix: properly shutdown subscriber stub on permanent streaming pull failure
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: api: pubsub, cla: yes

#557 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#562 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#563 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#565 samples(testing): add retry rule
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/utilities/State.java
  samples/snippets/src/main/java/utilities/StateProto.java
  samples/snippets/src/test/java/pubsub/SchemaIT.java
Labels: api: pubsub, cla: yes, samples

#567 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#541 feat: expose default client configs
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
Labels: api: pubsub, cla: yes

#560 docs: Remove experimental note for schema APIs
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/package-info.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaServiceGrpc.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/schema.proto
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#570 fix: update MessageDispatcher to not extend deadlines of messages which arrive early to 60s
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
Labels: api: pubsub, cla: yes

#574 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#577 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#580 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#581 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsub, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#583 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full
