Repository googleapis/java-pubsub, pull requests merged in 2021-01, with the labels that each got.

#478 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#476 fix: fix flakiness in subscriberIT integration test
  samples/snippets/src/test/java/pubsub/SubscriberIT.java
Labels: api: pubsub, cla: yes

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#370 docs: Document potentially unexpected blocking behavior of publish() method
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PublisherInterface.java
Labels: api: pubsub, cla: yes

#472 fix: adding deprecated tags to deprecated methods
  synth.py
Labels: api: pubsub, cla: yes

#492 chore: update subscription admin client variable names
  .kokoro/release/publish_javadoc.cfg
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  synth.metadata
Labels: api: pubsub, cla: yes, context: partial

#495 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: pubsub, automerge, cla: yes
