Repository googleapis/java-pubsub, pull requests merged in 2021-02, with the labels that each got.

#494 feat: add schema service to gapic
  .kokoro/build.sh
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/package-info.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSchemaServiceCallableFactory.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcSchemaServiceStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SchemaServiceStub.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSchemaService.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MockSchemaServiceImpl.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SchemaServiceClientTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java
  google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaServiceGrpc.java
  grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSchemaRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSchemaRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Encoding.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSchemaRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubProto.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Schema.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaName.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaProto.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaSettings.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaSettingsOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaView.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaResponseOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto
  proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/schema.proto
  synth.metadata
Labels: api: pubsub, cla: yes, context: full, context: partial

#499 chore: Re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#502 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#503 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#504 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#507 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#508 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#511 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#512 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#513 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#514 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#519 samples: remove duplicated testing
  .kokoro/continuous/java11-samples.cfg
  .kokoro/continuous/jave8-samples.cfg
  .kokoro/nightly/java11-samples.cfg
  .kokoro/nightly/java8-samples.cfg
  .kokoro/presubmit/java11-samples.cfg
  .kokoro/presubmit/java8-samples.cfg
  .kokoro/run_samples_tests.sh
Labels: api: pubsub, cla: yes, samples

#520 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#527 samples: fix region tags and remove version in pom
  samples/snippets/pom.xml
Labels: api: pubsub, cla: yes, samples

#529 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#531 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#532 samples: allow only one pair of region tags
  samples/snippets/pom.xml
Labels: api: pubsub, cla: yes, samples

#535 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#536 samples: update synth.py to exclude samples.yaml
  synth.py
Labels: api: pubsub, cla: yes, samples

#537 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes

#538 samples: add some comments
  samples/checkstyle-suppressions.xml
  samples/snippets/src/main/java/pubsub/CreateAvroSchemaExample.java
  samples/snippets/src/main/java/pubsub/PublishAvroRecordsExample.java
  samples/snippets/src/main/java/pubsub/PublishProtobufMessagesExample.java
  samples/snippets/src/main/java/utilities/State.java
  samples/snippets/src/main/java/utilities/StateProto.java
Labels: api: pubsub, cla: yes, samples

#548 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsub, automerge, cla: yes
