Repository googleapis/java-pubsub, pull requests merged in 2022-11, with the labels that each got.

#1382 deps: regenerating with new Protobuf (1.111.0-sp)
  .github/workflows/ci.yaml
  pom.xml
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/AcknowledgeRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/CreateSnapshotRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeadLetterPolicy.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSnapshotRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteSubscriptionRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeleteTopicRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DetachSubscriptionResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ExpirationPolicy.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSnapshotRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSubscriptionRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetTopicRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSchemasResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSnapshotsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSubscriptionsRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListSubscriptionsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSnapshotsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicSubscriptionsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicsRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ListTopicsResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/MessageStoragePolicy.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyAckDeadlineRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ModifyPushConfigRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublishRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublishResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PullResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PushConfig.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ReceivedMessage.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/RetryPolicy.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Schema.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SchemaSettings.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SeekResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Snapshot.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/StreamingPullResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Subscription.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/Topic.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSnapshotRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateSubscriptionRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UpdateTopicRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageRequestOrBuilder.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateMessageResponse.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaRequest.java
  proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ValidateSchemaResponse.java
  synth.metadata
Labels: kokoro:run, api: pubsub, size: xl

#1397 chore: skip opencensus-api enforcer rule (1.111.0-sp branch)
  pom.xml
Labels: api: pubsub, size: s

#1407 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: pubsub, size: m

#1410 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: pubsub, size: m

#1409 feat: next release from main branch is 1.122.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: pubsub, size: s

#1369 chore: restore missing native image configuration
  .kokoro/build.sh
Labels: api: pubsub, size: s
