Repository googleapis/java-pubsub, pull requests merged in 2022-01, with the labels that each got.

#967 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: api: pubsub, automerge, owlbot:ignore

#976 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: api: pubsub, automerge, owlbot:ignore

#978 samples: add subscription with filter example
  README.md
  samples/snippets/src/main/java/pubsub/CreateSubscriptionWithFiltering.java
  samples/snippets/src/test/java/pubsub/AdminIT.java
  samples/snippets/src/test/java/pubsub/SubscriberIT.java
Labels: api: pubsub, samples

#979 chore: additional sample reviewers
  .github/CODEOWNERS
Labels: api: pubsub, samples, owlbot:ignore
