Repository googleapis/java-pubsub, pull requests merged in 2023-10, with the labels that each got.

#1766 build: do not declare javadoc plugin version
  pom.xml
Labels: api: pubsub, size: xs

#1705 ci: javadoc as a required check
  .github/sync-repo-settings.yaml
Labels: api: pubsub, size: xs

#1762 docs: Adding a GCS subscription example
  README.md
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsub/CreateCloudStorageSubscriptionExample.java
Labels: api: pubsub, size: m

#1794 docs: renaming the CreateUnwrappedPushSubscription File
  README.md
  samples/snippets/src/main/java/pubsub/CreateUnwrappedPushSubscriptionExample.java
Labels: api: pubsub, size: xs

#1805 chore: Set blunderbuss config to auto-assign issues and PRs
  .github/blunderbuss.yml
Labels: api: pubsub, owlbot:ignore, size: xs
