Repository googleapis/java-pubsub, pull requests merged in 2024-08, with the labels that each got.

#2143 chore: secure hermetic_library_generation workflow
  .github/workflows/hermetic_library_generation.yaml
Labels: api: pubsub, automerge, size: s

#2144 chore: use sdk-platform-java-config instead of java-shared-config
  google-cloud-pubsub-bom/pom.xml
Labels: api: pubsub, automerge, size: xs

#2068 chore: Regenerate us-states.proto to no longer reference removed methods
  samples/snippets/src/main/java/utilities/StateProto.java
Labels: api: pubsub, size: l
